debug

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -42,12 +42,12 @@ jobs:
           sfdx force:mdapi:describemetadata > ../sfdx_types.json
           # cat ../sfdx_types.json    
           sfdx_types_status=$(cat ../sfdx_types.json | jq '.status')
-          if [ $sfdx_types_status -ne 0 ]; then
-            echo "ERROR unable to read Salesforce Metadata Types"
-            echo cat sfdx_login.json | jq '.message'
-            exit 1            
-          fi
+          # if [ $sfdx_types_status -ne 0 ]; then
+          #   echo "ERROR unable to read Salesforce Metadata Types"
+          #   echo cat sfdx_login.json | jq '.message'
+          #   exit 1            
+          # fi
 
-          cat ../sfdx_types.json
+          # cat ../sfdx_types.json
           # sfdx_types=$(cat ../sfdx_types.json | jq -r '.result.metadataObjects[].xmlName')
           # echo $sfdx_types 
