debug

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -40,4 +40,16 @@ jobs:
           git checkout -q -b $temp_branch     
 
           sfdx force:mdapi:describemetadata > ../sfdx_types.json
-          cat ../sfdx_types.json    
+          # cat ../sfdx_types.json    
+          sfdx_types_status=$(cat ../sfdx_types.json | jq '.status')
+          if [ $sfdx_types_status -ne 0 ]; then
+            echo "ERROR unable to read Salesforce Metadata Types"
+            echo cat sfdx_login.json | jq '.message'
+            exit 1            
+          fi
+
+          sfdx_types=$(cat ../sfdx_types.json | jq jq -r '.result.metadataObjects[].xmlName')
+          for sfdx_type in $sfdx_types; do 
+            echo $sfdx_type
+            # retrieve_salesforce_type "$sfdx_type" &
+          done 
